run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - misspell
    - gofmt
    - goimports
  disable:
    - exhaustruct
    - gochecknoglobals

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
